### ISSUE TITLE
Request for feature

### ISSUE THREAD

**Issue by Kabeer3** [CivicDataLab/oci-assam-frontend#36]
Is your feature request related to a problem? Please describe.
---------------------------------------------------
Cannot search option from filters by typing. Example, in data hosting page, in the Buyer name filter, user would want to search for department by typing instead of scrolling through all the options., which is a long list.

Describe the solution you'd like.
---------------------------------------------------
 Search by typing feature needed. 

Additional context.
---------------------------------------------------
…

**Comment by PixeledCode** [comment]
added in #37
