### ISSUE TITLE
Filters not applied to Table View

### ISSUE THREAD

**Issue by varun-ag42** [CivicDataLab/oci-assam-frontend#52]
<img width="995" alt="Screenshot 2022-05-16 at 3 18 05 PM" src="https://user-images.githubusercontent.com/74787233/168566094-d9fd9bff-d07f-4bb4-a020-99d7fc123b08.png">

Hi, I noticed a slight issue with the Assam Public Procurement Explorer Data Analysis page. When we click on a KPI and apply any filter from the left hand side, it gets applied only to the Graphs and not to the Table View which remains the same regardless.

**Comment by PixeledCode** [comment]
fixes on 2ca8413d2479492f9f9608
