### ISSUE TITLE
Colour Change needed in KPI legend

### ISSUE THREAD

**Issue by varun-ag42** [CivicDataLab/oci-assam-frontend#54]
![Proportion of value awarded in single bid tenders](https://user-images.githubusercontent.com/74787233/169463612-22ff8378-7122-4ea8-a70f-e9d190ca3327.png)

Here, the colours for 'Single Bid' which is green and 'Other than Single Bid' which is currently Red needs to be switched. Single Bid should be Red and Other than Single Bid should be green.

**Comment by PixeledCode** [comment]
fixed in commit b6853d8a29102
